[build]
  base = "client"
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://jueldin-api.onrender.com"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"
