services:
  - type: web
    name: jueldin-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 30d
      - key: API_URL
        value: https://jueldin-api.onrender.com
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MPESA_CONSUMER_KEY
        sync: false  
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_PASSKEY
        sync: false
